---
### check-shib3idp-login configuration ###
username: "some_user"
password: "some_password"
unsolicited_login_baseurl: "https://idp.example.com/idp/profile/SAML2/Unsolicited/SSO"
provider_id: "https://sp.example.com"
shire: "https://sp.example.com/Shibboleth.sso/SAML2/POST"